repos:
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
    -   id: cpplint
        args: ["--filter=-build/header_guard,,-legal/copyright,-whitespace/indent,-whitespace/comments"]
    -   id: cppcheck
        args: [--language=c++]
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    - id: clang-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
